### ISSUE TITLE
Issue on HorizonXI latest patch

### ISSUE THREAD

**Issue by 130bb** [mousseng/xitools#24]
The UI for tracking debuffs doesn't show the BLM ones now, looks cut off.

![image](https://github.com/mousseng/xitools/assets/10252328/26651015-591c-493f-bf6e-5172f4a3e0cd)

**Comment by mousseng** [comment]
this normally happens when you have a font larger than 14pt, and the default did change to 16pt (i think) some time ago. if you'd like to go back to 14pt, [you can follow the instructions in the Ashita discord](https://discord.com/channels/264673946257850368/693261203958661240/1185029451885596843); or you might consider fiddling with the settings file to change the window width:

```lua
settings["tools"]["tgt"]["mainWindow"]["size"][1] = 276;
settings["tools"]["tgt"]["subWindow"]["size"][1] = 276;
settings["tools"]["tgt"]["totWindow"]["size"][1] = 276;
```

but realistically, i wouldn't expect an actual _fix_ for this anytime soon.

**Comment by 130bb** [comment]
> this normally happens when you have a font larger than 14pt, and the default did change to 16pt (i think) some time ago. if you'd like to go back to 14pt, [you can follow the instructions in the Ashita discord](https://discord.com/channels/264673946257850368/693261203958661240/1185029451885596843); or you might consider fiddling with the settings file to change the window width:
> 
> ```lua
> settings["tools"]["tgt"]["mainWindow"]["size"][1] = 276;
> settings["tools"]["tgt"]["subWindow"]["size"][1] = 276;
> settings["tools"]["tgt"]["totWindow"]["size"][1] = 276;
> ```
> 
> but realistically, i wouldn't expect an actual _fix_ for this anytime soon.

Thanks for the quick response, I have adjusted the values to 320 and it is ok now!
